FROM rust:1.93-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
    valgrind \
    curl \
    ca-certificates \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
